### ISSUE TITLE
Error from npm test on Mac OS

### ISSUE THREAD

**Issue by danielearwicker** [dumbmatter/fakeIndexedDB#1]
Using v2.0.1 of io.js, I cloned and did `npm install` and then `npm test` and got:

	W3C IDBCursor.advance Tests
	    asyncness
	      1) "before all" hook
	
	  0 passing (15ms)
	  1 failing
	
	  1) W3C IDBCursor.advance Tests asyncness "before all" hook:
	     Uncaught TypeError: database._rawDatabase.transactions.find is not a function
	      at confirmActiveVersionchangeTransaction (lib/FDBDatabase.js:19:58)
	      at FDBDatabase.createObjectStore (lib/FDBDatabase.js:65:27)
	      at FDBOpenDBRequest.open.onupgradeneeded (test/w3c/IDBCursor.advance.js:19:35)
	      at invokeEventListeners (lib/EventTarget.js:32:27)
	      at FDBOpenDBRequest.dispatchEvent (lib/EventTarget.js:82:13)
	      at waitForOthersClosed (lib/FDBFactory.js:132:17)
	      at runVersionchangeTransaction (lib/FDBFactory.js:162:5)
	      at openDatabase (lib/FDBFactory.js:186:9)
	      at null.<anonymous> (lib/FDBFactory.js:251:13)
	
	
	
	
	npm ERR! Darwin 14.1.0
	npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "mocha"
	npm ERR! node v2.0.1
	npm ERR! npm  v2.9.0
	npm ERR! code ELIFECYCLE
	npm ERR! fake-indexeddb@1.0.2 mocha: `mocha --harmony --timeout 5000 test/w3c test/fakeIndexedDB`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the fake-indexeddb@1.0.2 mocha script 'mocha --harmony --timeout 5000 test/w3c test/fakeIndexedDB'.
	npm ERR! This is most likely a problem with the fake-indexeddb package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     mocha --harmony --timeout 5000 test/w3c test/fakeIndexedDB
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls fake-indexeddb
	npm ERR! There is likely additional logging output above.
	
	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/danielearwicker/github/fakeIndexedDB/npm-debug.log
	npm ERR! Test failed.  See above for more details.

**Comment by dumbmatter** [comment]
Thanks for the bug report! It slipped my mind that io.js doesn't support ES6 array features as well as Node.js (which is really weird given that one of their main goals is ES6 support).
