### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by TvoroG** [dumbmatter/fakeIndexedDB#33]
Hey! Thanks for this lib!

I'm trying to use fakeIndexedDB in node environment and have the following code:
```
import FDBCursor = require("fake-indexeddb/lib/FDBCursor");
```
Just trying to import fdbcursor but it throws error:
```
    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)

      at extendStatics (node_modules/fake-indexeddb/build/FDBCursorWithValue.js:7:16)
      at __extends (node_modules/fake-indexeddb/build/FDBCursorWithValue.js:10:9)
      at node_modules/fake-indexeddb/build/FDBCursorWithValue.js:18:5
      at Object.<anonymous> (node_modules/fake-indexeddb/build/FDBCursorWithValue.js:28:2)
```

I found that it is because of circular import.

What should i do?

**Comment by TvoroG** [comment]
It gets compiled to this:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const FDBCursor = require("fake-indexeddb/lib/FDBCursor");
```

**Comment by TvoroG** [comment]
I'm using following command to compile it:
```
tsc --skipLibCheck --target es6 --module commonjs --outDir ...
```

**Comment by TvoroG** [comment]
Cool! Thanks for quick response! :)

**Comment by TvoroG** [comment]
Thanks! It works now.

About my use case: i'm writing custom [testEnvironment](https://jestjs.io/docs/en/configuration#testenvironment-string) for jest and want to extend this.global with fakeIndexedDB:
```
require("fake-indexeddb"); // workaround
import FDBCursor = require("fake-indexeddb/lib/FDBCursor");
import FDBCursorWithValue = require("fake-indexeddb/lib/FDBCursorWithValue");
import FDBFactory = require("fake-indexeddb/lib/FDBFactory");
...

export function makeIndexedDBEnv() {
    return {
        indexedDB: new FDBFactory(), // to not worry about resetting
        IDBCursor: FDBCursor,
        IDBCursorWithValue: FDBCursorWithValue,
        ...
    }
}
```
```
class CustomEnvironment extends NodeEnvironment {
  ...
  async setup() {
    await super.setup();
    const idbEnv = makeIndexedDBEnv();
    Object.assign(this.global, idbEnv);
    ...
  }
}
```
