### ISSUE TITLE
3.1.6 regression: `ReferenceError: setImmediate is not defined`

### ISSUE THREAD

**Issue by ai** [dumbmatter/fakeIndexedDB#71]
After updating to `3.1.6` I got an error:

```
ReferenceError: setImmediate is not defined
      at Object.<anonymous> (node_modules/fake-indexeddb/build/lib/scheduling.js:28:21)
      at Object.<anonymous> (node_modules/fake-indexeddb/build/FDBTransaction.js:33:20)
      at Object.<anonymous> (node_modules/fake-indexeddb/build/FDBDatabase.js:27:24)
      at Object.<anonymous> (node_modules/fake-indexeddb/build/FDBFactory.js:30:21)
      at Object.<anonymous> (node_modules/fake-indexeddb/build/fakeIndexedDB.js:3:20)
      at Object.<anonymous> (node_modules/fake-indexeddb/build/index.js:3:23)
```

I am using Jest 27.3.1 with `"testEnvironment": "jsdom"`.

**Comment by dumbmatter** [comment]
Thanks, fixed in 3.1.7
