### ISSUE TITLE
getAll (using backboard) fails with fakeIndexedDB but works in Chrome

### ISSUE THREAD

**Issue by bsr203** [dumbmatter/fakeIndexedDB#9]
Hi, I met with below error while using `getAll`. Below is part of the code.

```
  async all() {
    const db = await connect();
    return db.sess.getAll();
  }
```
in my test
```
const values = await sess.all();
 assert(values.length === 3);
```

```
1) Session all, find:
     TypeError: Cannot read property 'apply' of undefined
      at node_modules/backboard/dist/lib/wrap-request.js:24:96
      at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
      at exports.default (node_modules/backboard/dist/lib/wrap-request.js:18:12)
      at ObjectStore.(anonymous function) [as getAll] (node_modules/backboard/dist/lib/ObjectStore.js:112:38)
      at Session._callee3$ (src/frontend/bundles/layout/services/Session.js:379:59)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:95:21)
      at step (Session.js:6:37)
      at Session.js:6:37
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

```

I tried with `bluebird`, still the same error
```
  1) Session all, find:
     TypeError: Cannot read property 'apply' of undefined
      at node_modules/backboard/dist/lib/wrap-request.js:24:96
      at Promise._execute (node_modules/bluebird/js/release/debuggability.js:272:9)
      at Promise._resolveFromExecutor (node_modules/bluebird/js/release/promise.js:475:18)
      at new Promise (node_modules/bluebird/js/release/promise.js:77:14)
      at exports.default (node_modules/backboard/dist/lib/wrap-request.js:18:12)
      at ObjectStore.(anonymous function) [as getAll] (node_modules/backboard/dist/lib/ObjectStore.js:112:38)
      at Session._callee3$ (Session.js:21:15)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:336:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:95:21)
      at step (Session.js:1:1)
      at Session.js:1:1
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

It works fine in Chrome Canary

```
_recordStoreFactory = recordStoreFactory(mode, resolve, reject)[method]
getAll() { [native code] }
```

**Comment by dumbmatter** [comment]
Yeah, I didn't put `getAll` in this because it was not part of the original IndexedDB standard. It's been added subsequently and some browsers support it.

Fortunately, I also wrote https://www.npmjs.com/package/indexeddb-getall-shim which you can use. It assumes global variables for IndexedDB stuff, so require it after setting globals like https://github.com/dumbmatter/backboard/blob/master/test/root.js#L31-L38

Also, a PR to add getAll directly to fakeIndexedDB would be welcome :)

**Comment by bsr203** [comment]
thanks for your help. It's Friday eve, so will get back in couple of days  :-)

**Comment by bsr203** [comment]
Hi,

I tried `indexeddb-getall-shim` and worked great! I would close it for now, as testing may take bit of my time and will contribute when I get more familiar with this library and spec. thanks again for all your work.
bsr.
